Parameters:

  Prefix:
    Type: String

  PrivateCidrBlock:
    Type: String
    Description: Primary CIDR block
    Default: 192.168.0.0/16
    AllowedPattern: "(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.\
                     (25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.\
                     (25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.\
                     (25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/\
                     (1[6-9]|2[0-8])"

  TransitCidrBlock:
    Type: String
    Description: Secondary CIDR block
    AllowedPattern: "(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.\
                     (25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.\
                     (25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.\
                     (25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/\
                     (1[6-9]|2[0-8])"

  TransitGatewayId:
    Type: String
    Default: tgw-1234abcd1234abcd1

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref PrivateCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub '${Prefix}-vpc'

  SecondaryCidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      CidrBlock: !Ref TransitCidrBlock
      VpcId: !Ref VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${Prefix}-igw'

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC




  Transit1:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - SecondaryCidrBlock
    - InternetGatewayAttachment
    Properties:
      TemplateURL: !Sub 'https://${AWS::AccountId}-cloudformation.s3.amazonaws.com/VPC/TransitSubnet.yaml'
      Parameters:
        VpcName: !Ref Prefix
        VpcId: !Ref VPC
        AvailabilityZone: !Select [ 0, !GetAZs '' ]
        CidrBlock: !Select [ 0, !Cidr [ !Ref TransitCidrBlock, 2, 4 ] ]

  Transit2:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - SecondaryCidrBlock
    - InternetGatewayAttachment
    Properties:
      TemplateURL: !Sub 'https://${AWS::AccountId}-cloudformation.s3.amazonaws.com/VPC/TransitSubnet.yaml'
      Parameters:
        VpcName: !Ref Prefix
        VpcId: !Ref VPC
        AvailabilityZone: !Select [ 1, !GetAZs '' ]
        CidrBlock: !Select [ 1, !Cidr [ !Ref TransitCidrBlock, 2, 4 ] ]




  TransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      SubnetIds:
        - !GetAtt [ Transit1, Outputs.Subnet ]
        - !GetAtt [ Transit2, Outputs.Subnet ]
      TransitGatewayId: !Ref TransitGatewayId
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${Prefix}-tgwa'

  TransitRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${Prefix}-transit-rtb'

  TransitGatewayRoute:
    Type: AWS::EC2::Route
    DependsOn: TransitGatewayAttachment
    Properties:
      RouteTableId: !Ref TransitRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayId: !Ref TransitGatewayId

  Transit1SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref TransitRouteTable
      SubnetId: !GetAtt [ Transit1, Outputs.Subnet ]

  Transit2SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref TransitRouteTable
      SubnetId: !GetAtt [ Transit2, Outputs.Subnet ]




  Private1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWS::AccountId}-cloudformation.s3.amazonaws.com/VPC/PrivateSubnet.yaml'
      Parameters:
        VpcName: !Ref Prefix
        VpcId: !Ref VPC
        AvailabilityZone: !Select [ 0, !GetAZs '' ]
        CidrBlock: !Select [ 0, !Cidr [ !Ref PrivateCidrBlock, 2, 8 ] ]
        NatGateway: !GetAtt [ Transit1, Outputs.NatGateway ]

  Private2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWS::AccountId}-cloudformation.s3.amazonaws.com/VPC/PrivateSubnet.yaml'
      Parameters:
        VpcName: !Ref Prefix
        VpcId: !Ref VPC
        AvailabilityZone: !Select [ 1, !GetAZs '' ]
        CidrBlock: !Select [ 1, !Cidr [ !Ref PrivateCidrBlock, 2, 8 ] ]
        NatGateway: !GetAtt [ Transit2, Outputs.NatGateway ]




Outputs:

  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC

  TransitSubnet1:
    Description: A reference to the transit subnet in the 1st Availability Zone
    Value: !GetAtt [ Transit1, Outputs.Subnet ]

  TransitSubnet2:
    Description: A reference to the transit subnet in the 2nd Availability Zone
    Value: !GetAtt [ Transit2, Outputs.Subnet ]

  PrivateSubnet1:
    Description: A reference to the private subnet in the 1st Availability Zone
    Value: !GetAtt [ Private1, Outputs.Subnet ]

  PrivateSubnet2:
    Description: A reference to the private subnet in the 2nd Availability Zone
    Value: !GetAtt [ Private2, Outputs.Subnet ]
