Parameters:
  VpcName:
    Type: String

  VpcId:
    Type: AWS::EC2::VPC::Id

  AvailabilityZone:
    Type: String

  CidrBlock:
    Type: String

  NatGateway:
    Type: String
  
Resources:
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Ref AvailabilityZone
      CidrBlock: !Ref CidrBlock
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref VpcName, 'private', !Select [ 2, !Split [ '-', !Ref AvailabilityZone ] ] ] ]

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref VpcName, 'private', !Select [ 2, !Split [ '-', !Ref AvailabilityZone ] ], 'rtb' ] ]

  NatGatewayRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet

Outputs:
  Subnet:
    Value: !Ref Subnet

  RouteTable:
    Value: !Ref RouteTable
