Parameters:
  VpcName:
    Type: String

  VpcId:
    Type: AWS::EC2::VPC::Id

  AvailabilityZone:
    Type: String

  CidrBlock:
    Type: String
  
Resources:
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Ref AvailabilityZone
      CidrBlock: !Ref CidrBlock
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref VpcName, 'transit', !Select [ 2, !Split [ '-', !Ref AvailabilityZone] ] ] ]

  NatGatewayEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEip.AllocationId
      SubnetId: !Ref Subnet
      Tags:
        - Key: Name
          Value:  !Join [ '-', [ !Ref VpcName, 'transit', !Select [ 2, !Split [ '-', !Ref AvailabilityZone ] ], 'nat' ] ]

Outputs:
  Subnet:
    Value: !Ref Subnet

  NatGateway:
    Value: !Ref NatGateway
